package com.midtrans.sdk.uikit.internal.view

import androidx.compose.ui.graphics.Color
import java.util.prefs.BackingStoreException

object SnapColors {

    const val BACKGROUND_BORDER_SOLID_SECONDARY = 0XE6E9EF
    const val BACKGROUND_BORDER_SOLID_PRIMARY = 0XDBDFE7
    const val BACKGROUND_FILL_PRIMARY = 0XFFFFFF
    const val BACKGROUND_FILL_SECONDARY = 0XEFF2F6
    const val BACKGROUND_FILL_HIGHLIGHT = 0XE8EBEF
    const val BACKGROUND_FILL_BRAND = 0X3A5EAB
    const val BACKGROUND_FILL_INVERSE = 0X2044
    const val BACKGROUND_FILL_LIGHT = 0XFFFBFE

    const val TEXT_PRIMARY = 0X2D2E34
    const val TEXT_SECONDARY = 0X4F515C
    const val TEXT_MUTED = 0X8E919B
    const val TEXT_INVERSE = 0XFFFFFF
    const val TEXT_BRAND = 0X07ADDC
    const val TEXT_DISABLED = 0X9A9EAA
    const val ICON_PRIMARY = 0X2D2E34
    const val ICON_INVERSE = 0XFFFFFF
    const val ICON_MUTED = 0X8E919B
    const val ICON_BRAND = 0X7ADDC
    const val ICON_DISABLED = 0X9A9EAA

    const val LINK = 0X1F44E5
    const val LINK_HOVER = 0X3E62FE
    const val LINK_ACTIVE = 0X1F44E5
    const val LINK_VISITED = 0XC643C1

    const val INTERACTIVE_FILL_BRAND_DEFAULT = 0X07ADDC
    const val INTERACTIVE_FILL_BRAND_HOVER = 0X41CFF8
    const val INTERACTIVE_FILL_BRAND_ACTIVE = 0X054FBF

    const val INTERACTIVE_FILL_DEFAULT = 0X5070FD
    const val INTERACTIVE_FILL_HOVER = 0X85A2F9
    const val INTERACTIVE_FILL_ACTIVE = 0X1C3ABB
    const val INTERACTIVE_BORDER_INPUT = 0XDCDFE6
    const val INTERACTIVE_BORDER_DOTTED = 0XDCDFE6
    const val INTERACTIVE_DISABLED = 0XF1F3F6
    const val INTERACTIVE_FOCUS = 0X054FBF
    const val INTERACTIVE_BORDER_SUPPORT = 0XF27E89
    const val INTERACTIVE_BORDER_ACTION = 0X4F515C
    const val INTERACTIVE_FILL_INVERSE = 0X383942

    const val SUPPORT_DANGER_DEFAULT = 0XF3536B
    const val SUPPORT_DANGER_HOVER = 0XF3637A
    const val SUPPORT_DANGER_ACTIVE = 0XC32E52
    const val SUPPORT_DANGER_FILL = 0XFEE1E7
    const val SUPPORT_WARNING_DEFAULT = 0XFFCE45
    const val SUPPORT_WARNING_HOVER = 0XFFDD80
    const val SUPPORT_WARNING_ACTIVE = 0XD8991F
    const val SUPPORT_WARNING_FILL = 0XFFF5E3
    const val SUPPORT_SUCCESS_DEFAULT = 0X00D5B5
    const val SUPPORT_SUCCESS_HOVER = 0X84E1CC
    const val SUPPORT_SUCCESS_ACTIVE = 0X87973
    const val SUPPORT_SUCCESS_FILL = 0XE8FBF7
    const val SUPPORT_INFO_DEFAULT = 0X5070FD
    const val SUPPORT_INFO_HOVER = 0X85A2F9
    const val SUPPORT_INFO_ACTIVE = 0X1C3ABB
    const val SUPPORT_INFO_FILL = 0XE3EDFF
    const val SUPPORT_NEUTRAL_FILL = 0XEFF2F6

    const val TRANSPARENT = 0L

    const val OVERLAY_BLACK = 0X32333A
    const val OVERLAY_WHITE = 0XFFFFFF

    const val LINE_LIGHT_MUTED = 0XE8E8E8

    fun getARGBColor(color: Int): Color {
        return Color((color.toLong() + (0xFF000000).toLong()))
    }
}